[package]
name = "tetris-game"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
dotenvy = "0.15.7"
rand = "0.8.5"
raylib = { version = "5.0.1", features = ["wayland"] }
tetris-core = { path = "../tetris-core" }
